### ISSUE TITLE
Problem with installing package

### ISSUE THREAD

**Issue by davidcmh** [anvaka/ngraph.gexf#1]
Hi, I encountered an error while installing ngraph.gexf package. Will greatly appreciate it if you could provide some guide as to how to overcome it.

The following is a quick log, there is additional log output in a separate file npm-debug.log that I could upload if it's required.

Thanks,
David

npm ERR! Failed at the libxmljs@0.8.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libxmljs

**Comment by anvaka** [comment]
Thank you for reporting this!

I was able to reproduce the error, and after updating dependencies it should be installed properly. The fixed version is published to npm as `v0.0.8`

**Comment by davidcmh** [comment]
It works now, thanks for the quick fix!
